name: Sync and Rename whereIsTheMoodRobot Images to cover/16 Folder

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message for syncing and renaming images'
        required: false
        default: 'Sync and rename images from pages/musicpool-db/covers/whereIsTheMoodRobot to cover/16 from 1.jpg-13.jpg to 352.jpg-364.jpg'

jobs:
  sync_and_rename:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the Destination Repository
      - name: Checkout Destination Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main

      # Step 2: Clone the Source Repository
      - name: Clone Source Repository
        run: |
          echo "Cloning source repository..."
          git clone https://github.com/DbRDYZmMRu/Ut67QIwioF.git source-repo || echo "Failed to clone source repo. Check URL."

      # Step 3: Debug Source Repository Contents
      - name: List Source Repository Contents
        run: |
          echo "Listing contents of source-repo:"
          ls -laR source-repo || echo "Source repository is empty or not cloned."
          if [ -d "source-repo/pages/musicpool-db/covers/whereIsTheMoodRobot" ]; then
            echo "pages/musicpool-db/covers/whereIsTheMoodRobot folder exists in source-repo."
            ls -la source-repo/pages/musicpool-db/covers/whereIsTheMoodRobot
          else
            echo "pages/musicpool-db/covers/whereIsTheMoodRobot folder does not exist in source-repo."
          fi

      # Step 4: Copy and Rename Images to cover/16
      - name: Copy and Rename Images
        run: |
          echo "Creating cover/16 directory..."
          mkdir -p cover/16
          if [ -d "source-repo/pages/musicpool-db/covers/whereIsTheMoodRobot" ]; then
            echo "Copying and renaming images from source-repo/pages/musicpool-db/covers/whereIsTheMoodRobot to cover/16..."
            for file in source-repo/pages/musicpool-db/covers/whereIsTheMoodRobot/[0-9]*.jpg; do
              if [ -f "$file" ]; then
                # Extract the numerical part of the filename (e.g., "1" from "1.jpg")
                filename=$(basename "$file" .jpg)
                if [[ "$filename" =~ ^([0-9]+)$ ]]; then
                  old_number=${BASH_REMATCH[1]}
                  # Ensure the number is between 1 and 13
                  if [ "$old_number" -ge 1 ] && [ "$old_number" -le 13 ]; then
                    # Calculate new number by adding 351 (e.g., 1 + 351 = 352)
                    new_number=$((old_number + 351))
                    new_name="cover/16/${new_number}.jpg"
                    echo "Copying and renaming $file to $new_name"
                    cp "$file" "$new_name" || echo "Failed to copy $file to $new_name"
                  else
                    echo "Skipping $file: Number $old_number is outside the range 1-13"
                  fi
                else
                  echo "Skipping $file: Filename does not match expected format [1-13].jpg"
                fi
              fi
            done
            echo "Listing contents of cover/16 after copy and rename:"
            ls -la cover/16
          else
            echo "Source folder pages/musicpool-db/covers/whereIsTheMoodRobot not found in source-repo. Skipping copy."
          fi

      # Step 5: Configure Git User
      - name: Configure Git User
        run: |
          echo "Configuring Git user..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Step 6: Commit and Push Changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Adding cover/16 to git..."
          git add cover/16
          echo "Git status after add:"
          git status
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Committing changes..."
            git commit -m "${{ github.event.inputs.commit_message || 'Sync and rename images from pages/musicpool-db/covers/whereIsTheMoodRobot to cover/16 from 1.jpg-13.jpg to 352.jpg-364.jpg' }}"
            echo "Pushing changes..."
            git push origin main
          fi