name: Rename MP3 Files in audio/1

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message for file renaming'
        required: false
        default: 'Rename MP3 files in audio/1 based on provided list'

jobs:
  rename_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main

      # Step 2: Debug audio/1 Folder Contents
      - name: List audio/1 Folder Contents
        run: |
          echo "Listing contents of audio/1 folder:"
          ls -la audio/1 || echo "audio/1 folder is empty or does not exist."

      # Step 3: Rename Files in audio/1
      - name: Rename Files
        run: |
          echo "Renaming files in audio/1..."
          # Define the mapping list as an array
          declare -A title_map=(
            ["What is love"]="1"
            ["Real friends"]="2"
            ["Spotlight"]="3"
            ["Bleeding heart"]="4"
            ["Rollie dreams"]="5"
            ["Bad Vibez"]="6"
            ["My heart"]="7"
            ["Interlude"]="8"
            ["What is real"]="9"
            ["Sunday special"]="10"
            ["Hurt you"]="11"
            ["Two bad bitches"]="12"
            ["What's the price"]="13"
          )
          # Loop through MP3 files in audio/1
          for file in audio/1/*.mp3; do
            if [ -f "$file" ]; then
              # Extract title by removing leading number and non-alphanumeric chars
              filename=$(basename "$file" .mp3)
              title=$(echo "$filename" | sed 's/^[0-9]\+[^[:alnum:]]*//')
              echo "Processing file: $file (extracted title: $title)"
              # Convert title to lowercase for case-insensitive matching
              title_lower=$(echo "$title" | tr '[:upper:]' '[:lower:]')
              matched=false
              # Loop through title_map to find a match
              for list_title in "${!title_map[@]}"; do
                list_title_lower=$(echo "$list_title" | tr '[:upper:]' '[:lower:]')
                # Check if all significant words in list_title appear in title_lower
                match=true
                # Split list_title into words (ignoring spaces, punctuation)
                for word in $list_title_lower; do
                  if ! echo "$title_lower" | grep -q -w "$word"; then
                    match=false
                    break
                  fi
                done
                if [ "$match" = true ]; then
                  new_name="audio/1/${title_map[$list_title]}.mp3"
                  echo "Matched '$title' to '$list_title', renaming to $new_name"
                  mv "$file" "$new_name"
                  matched=true
                  break
                fi
              done
              if [ "$matched" = false ]; then
                echo "No match found for '$title'"
              fi
            fi
          done

      # Step 4: Debug audio/1 Folder After Renaming
      - name: List audio/1 Folder After Renaming
        run: |
          echo "Listing contents of audio/1 folder after renaming:"
          ls -la audio/1

      # Step 5: Configure Git User
      - name: Configure Git User
        run: |
          echo "Configuring Git user..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Step 6: Commit and Push Changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Adding changes to git..."
          git add audio/1
          echo "Git status after add:"
          git status
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Committing changes..."
            git commit -m "${{ github.event.inputs.commit_message }}"
            echo "Pushing changes..."
            git push origin main
          fi