name: Rename MP3 Files in audio/16 with Numerical Mapping

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message for file renaming'
        required: false
        default: 'Rename MP3 files in audio/16 from 1.mp3-13.mp3 to 352.mp3-364.mp3'

jobs:
  rename_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main

      # Step 2: Debug audio/16 Folder Contents
      - name: List audio/16 Folder Contents
        run: |
          echo "Listing contents of audio/16 folder:"
          ls -la audio/16 || echo "audio/16 folder is empty or does not exist."

      # Step 3: Rename Files in audio/16
      - name: Rename Files
        run: |
          echo "Renaming files in audio/16..."
          for file in audio/16/[0-9]*.mp3; do
            if [ -f "$file" ]; then
              # Extract the numerical part of the filename (e.g., "1" from "1.mp3")
              filename=$(basename "$file" .mp3)
              if [[ "$filename" =~ ^([0-9]+)$ ]]; then
                old_number=${BASH_REMATCH[1]}
                # Ensure the number is between 1 and 13
                if [ "$old_number" -ge 1 ] && [ "$old_number" -le 13 ]; then
                  # Calculate new number by adding 351 (e.g., 1 + 351 = 352)
                  new_number=$((old_number + 351))
                  new_name="audio/16/${new_number}.mp3"
                  echo "Renaming $file to $new_name"
                  mv "$file" "$new_name"
                else
                  echo "Skipping $file: Number $old_number is outside the range 1-13"
                fi
              else
                echo "Skipping $file: Filename does not match expected format [1-13].mp3"
              fi
            fi
          done

      # Step 4: Debug audio/16 Folder After Renaming
      - name: List audio/16 Folder After Renaming
        run: |
          echo "Listing contents of audio/16 folder after renaming:"
          ls -la audio/16

      # Step 5: Configure Git User
      - name: Configure Git User
        run: |
          echo "Configuring Git user..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Step 6: Commit and Push Changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Adding changes to git..."
          git add audio/16
          echo "Git status after add:"
          git status
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Committing changes..."
            git commit -m "${{ github.event.inputs.commit_message }}"
            echo "Pushing changes..."
            git push origin main
          fi