name: Rename MP3 Files in audio/14 with New List

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message for file renaming'
        required: false
        default: 'Rename MP3 files in audio/14 based on new list starting from 298'

jobs:
  rename_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main

      # Step 2: Debug audio/14 Folder Contents
      - name: List audio/14 Folder Contents
        run: |
          echo "Listing contents of audio/14 folder:"
          ls -la audio/14 || echo "audio/14 folder is empty or does not exist."

      # Step 3: Rename Files in audio/14
      - name: Rename Files
        run: |
          echo "Renaming files in audio/14..."
          # Define the mapping list as an array, starting from 298
          declare -A title_map=(
            ["Oliver Sacks"]="298"
            ["Oliver Sacks II"]="299"
            ["Palacio de la Zarzuela"]="300"
            ["The preacher"]="301"
            ["Rick reflection"]="302"
            ["End of summer"]="303"
            ["Sex is everything"]="304"
            ["Fool for you"]="305"
            ["Hathaway"]="306"
            ["Crush"]="307"
            ["Jealousy"]="308"
            ["Obligations"]="309"
            ["Rust"]="310"
            ["Best cardigan"]="311"
            ["Unwilling"]="312"
            ["Applish"]="313"
            ["Home alone"]="314"
            ["Aureole sigh"]="315"
            ["First lines"]="316"
            ["Spaghetti code"]="317"
            ["Fire"]="318"
            ["Fish"]="319"
            ["Greener"]="320"
            ["Lens"]="321"
            ["Keyhole"]="322"
            ["Bright-eyed"]="323"
            ["Cut in fame"]="324"
            ["Feel good"]="325"
            ["Adios"]="326"
            ["Woah"]="327"
            ["Locked in"]="328"
            ["Heartbeat"]="329"
            ["Barefoot"]="330"
          )
          # Loop through MP3 files in audio/14
          for file in audio/14/*.mp3; do
            if [ -f "$file" ]; then
              # Extract title by removing leading number and non-alphanumeric chars
              filename=$(basename "$file" .mp3)
              title=$(echo "$filename" | sed 's/^[0-9]\+[^[:alnum:]]*//')
              echo "Processing file: $file (extracted title: $title)"
              # Convert title to lowercase for case-insensitive matching
              title_lower=$(echo "$title" | tr '[:upper:]' '[:lower:]')
              matched=false
              # Loop through title_map to find a match
              for list_title in "${!title_map[@]}"; do
                list_title_lower=$(echo "$list_title" | tr '[:upper:]' '[:lower:]')
                # Check if all significant words in list_title appear in title_lower
                match=true
                # Split list_title into words (ignoring spaces, punctuation)
                for word in $list_title_lower; do
                  if ! echo "$title_lower" | grep -q -w "$word"; then
                    match=false
                    break
                  fi
                done
                if [ "$match" = true ]; then
                  new_name="audio/14/${title_map[$list_title]}.mp3"
                  echo "Matched '$title' to '$list_title', renaming to $new_name"
                  mv "$file" "$new_name"
                  matched=true
                  break
                fi
              done
              if [ "$matched" = false ]; then
                echo "No match found for '$title'"
              fi
            fi
          done

      # Step 4: Debug audio/14 Folder After Renaming
      - name: List audio/14 Folder After Renaming
        run: |
          echo "Listing contents of audio/14 folder after renaming:"
          ls -la audio/14

      # Step 5: Configure Git User
      - name: Configure Git User
        run: |
          echo "Configuring Git user..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Step 6: Commit and Push Changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Adding changes to git..."
          git add audio/14
          echo "Git status after add:"
          git status
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Committing changes..."
            git commit -m "${{ github.event.inputs.commit_message }}"
            echo "Pushing changes..."
            git push origin main
          fi