name: Rename JSON Files and It’s POP Folder in json

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message for renaming JSON files and It’s POP folder'
        required: false
        default: 'Rename JSON files in json/It’s POP to 262.json to 283.json and rename folder to json/12'

jobs:
  rename_files_and_folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main

      # Step 2: Debug json Folder Contents
      - name: List json Folder Contents
        run: |
          echo "Listing contents of json folder:"
          ls -laR json || echo "json folder is empty or does not exist."
          shopt -s nocaseglob
          if ls json/[Ii][Tt][Ss]*[Pp][Oo][Pp] 2>/dev/null; then
            folder=$(ls -d json/[Ii][Tt][Ss]*[Pp][Oo][Pp] | head -n 1)
            echo "Found folder: $folder"
            ls -la "$folder"
          else
            echo "json/It’s POP folder (any case) does not exist."
          fi
          shopt -u nocaseglob

      # Step 3: Rename JSON Files in json/It’s POP
      - name: Rename JSON Files
        run: |
          echo "Renaming JSON files in json/It’s POP to 262.json to 283.json..."
          shopt -s nocaseglob
          folder=$(ls -d json/[Ii][Tt][Ss]*[Pp][Oo][Pp] 2>/dev/null | head -n 1)
          if [ -n "$folder" ] && [ -d "$folder" ]; then
            # Define the mapping list as an array with adjusted numbers (1->262, 2->263, ..., 22->283)
            declare -A title_map=(
              ["Low life dirty rat"]="262"
              ["A seal"]="263"
              ["Summit"]="264"
              ["New hemp plant"]="265"
              ["Melly"]="266"
              ["Stuck in life"]="267"
              ["Heart census"]="268"
              ["Kevin Hart"]="269"
              ["Head"]="270"
              ["Imagination"]="271"
              ["Lonely note"]="272"
              ["Hubble"]="273"
              ["Take me out"]="274"
              ["Reward Money"]="275"
              ["Big fat lie"]="276"
              ["The calm"]="277"
              ["I don't know"]="278"
              ["I get the ghetto"]="279"
              ["Sliving"]="280"
              ["Bagging this home"]="281"
              ["Bag grips"]="282"
              ["Outro"]="283"
            )
            # Loop through JSON files in the folder
            for file in "$folder"/*.json; do
              if [ -f "$file" ]; then
                # Extract title by removing .json extension
                filename=$(basename "$file" .json)
                title="$filename"
                echo "Processing file: $file (extracted title: $title)"
                # Convert title to lowercase for case-insensitive matching
                title_lower=$(echo "$title" | tr '[:upper:]' '[:lower:]')
                # Replace common separators and apostrophes in title_lower for matching (e.g., "don't" to "dont")
                title_lower=$(echo "$title_lower" | sed "s/[']//g")
                matched=false
                # Loop through title_map to find a match
                for list_title in "${!title_map[@]}"; do
                  list_title_lower=$(echo "$list_title" | tr '[:upper:]' '[:lower:]')
                  list_title_lower=$(echo "$list_title_lower" | sed "s/[']//g")
                  # Check if all significant words in list_title appear in title_lower
                  match=true
                  # Split list_title into words (ignoring spaces, punctuation)
                  for word in $list_title_lower; do
                    if ! echo "$title_lower" | grep -q -w "$word"; then
                      match=false
                      break
                    fi
                  done
                  if [ "$match" = true ]; then
                    new_name="$folder/${title_map[$list_title]}.json"
                    echo "Matched '$title' to '$list_title', renaming to $new_name"
                    mv "$file" "$new_name" || echo "Failed to rename $file to $new_name"
                    matched=true
                    break
                  fi
                done
                if [ "$matched" = false ]; then
                  echo "No match found for '$title'"
                fi
              fi
            done
          else
            echo "json/It’s POP folder (any case) not found. Skipping JSON file renaming."
          fi
          shopt -u nocaseglob

      # Step 4: Rename json/It’s POP Folder to json/12
      - name: Rename It’s POP Folder
        run: |
          echo "Renaming json/It’s POP to json/12..."
          shopt -s nocaseglob
          folder=$(ls -d json/[Ii][Tt][Ss]*[Pp][Oo][Pp] 2>/dev/null | head -n 1)
          if [ -n "$folder" ] && [ -d "$folder" ]; then
            mv "$folder" json/12 || echo "Failed to rename $folder to json/12"
          else
            echo "json/It’s POP folder (any case) not found. Skipping folder renaming."
          fi
          shopt -u nocaseglob
          echo "Listing contents of json after renaming:"
          ls -laR json

      # Step 5: Configure Git User
      - name: Configure Git User
        run: |
          echo "Configuring Git user..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Step 6: Commit and Push Changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Adding json to git..."
          git add json
          echo "Git status after add:"
          git status
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Committing changes..."
            git commit -m "${{ github.event.inputs.commit_message || 'Rename JSON files in json/It’s POP to 262.json to 283.json and rename folder to json/12' }}"
            echo "Pushing changes..."
            git push origin main
          fi