name: Rename JSON Files and December 13 Folder in json

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message for renaming JSON files and December 13 folder'
        required: false
        default: 'Rename JSON files in json/December 13 to 44.json to 68.json and rename folder to json/3'

jobs:
  rename_files_and_folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main

      # Step 2: Debug json Folder Contents
      - name: List json Folder Contents
        run: |
          echo "Listing contents of json folder:"
          ls -laR json || echo "json folder is empty or does not exist."
          shopt -s nocaseglob
          if ls json/[Dd][Ee][Cc][Ee][Mm][Bb][Ee][Rr][[:space:]]13 2>/dev/null; then
            folder=$(ls -d json/[Dd][Ee][Cc][Ee][Mm][Bb][Ee][Rr][[:space:]]13 | head -n 1)
            echo "Found folder: $folder"
            ls -la "$folder"
          else
            echo "json/December 13 folder (any case) does not exist."
          fi
          shopt -u nocaseglob

      # Step 3: Rename JSON Files in json/December 13
      - name: Rename JSON Files
        run: |
          echo "Renaming JSON files in json/December 13 to 44.json to 68.json..."
          shopt -s nocaseglob
          folder=$(ls -d json/[Dd][Ee][Cc][Ee][Mm][Bb][Ee][Rr][[:space:]]13 2>/dev/null | head -n 1)
          if [ -n "$folder" ] && [ -d "$folder" ]; then
            # Define the mapping list as an array with adjusted numbers (1->44, 2->45, ..., 25->68)
            declare -A title_map=(
              ["Anarchy"]="44"
              ["December 13"]="45"
              ["Can't have you"]="46"
              ["Got a bitch a valve"]="47"
              ["Tom"]="48"
              ["Still can't swim"]="49"
              ["Well with her eff fame"]="50"
              ["Lili Fallon"]="51"
              ["Missing you"]="52"
              ["My girl"]="53"
              ["Forest"]="54"
              ["Flutter"]="55"
              ["No - 13 a bore"]="56"
              ["Partner"]="57"
              ["Something simple"]="58"
              ["Aperient flow"]="59"
              ["Six"]="60"
              ["Beethovenian"]="61"
              ["Outside"]="62"
              ["I think I am"]="63"
              ["Sound of tears"]="64"
              ["What's next"]="65"
              ["Scribbling with a gun"]="66"
              ["I'm okay"]="67"
              ["Milou Christmas"]="68"
            )
            # Loop through JSON files in the folder
            for file in "$folder"/*.json; do
              if [ -f "$file" ]; then
                # Extract title by removing .json extension
                filename=$(basename "$file" .json)
                title="$filename"
                echo "Processing file: $file (extracted title: $title)"
                # Convert title to lowercase for case-insensitive matching
                title_lower=$(echo "$title" | tr '[:upper:]' '[:lower:]')
                matched=false
                # Loop through title_map to find a match
                for list_title in "${!title_map[@]}"; do
                  list_title_lower=$(echo "$list_title" | tr '[:upper:]' '[:lower:]')
                  # Check if all significant words in list_title appear in title_lower
                  match=true
                  # Split list_title into words (ignoring spaces, punctuation)
                  for word in $list_title_lower; do
                    if ! echo "$title_lower" | grep -q -w "$word"; then
                      match=false
                      break
                    fi
                  done
                  if [ "$match" = true ]; then
                    new_name="$folder/${title_map[$list_title]}.json"
                    echo "Matched '$title' to '$list_title', renaming to $new_name"
                    mv "$file" "$new_name" || echo "Failed to rename $file to $new_name"
                    matched=true
                    break
                  fi
                done
                if [ "$matched" = false ]; then
                  echo "No match found for '$title'"
                fi
              fi
            done
          else
            echo "json/December 13 folder (any case) not found. Skipping JSON file renaming."
          fi
          shopt -u nocaseglob

      # Step 4: Rename json/December 13 Folder to json/3
      - name: Rename December 13 Folder
        run: |
          echo "Renaming json/December 13 to json/3..."
          shopt -s nocaseglob
          folder=$(ls -d json/[Dd][Ee][Cc][Ee][Mm][Bb][Ee][Rr][[:space:]]13 2>/dev/null | head -n 1)
          if [ -n "$folder" ] && [ -d "$folder" ]; then
            mv "$folder" json/3 || echo "Failed to rename $folder to json/3"
          else
            echo "json/December 13 folder (any case) not found. Skipping folder renaming."
          fi
          shopt -u nocaseglob
          echo "Listing contents of json after renaming:"
          ls -laR json

      # Step 5: Configure Git User
      - name: Configure Git User
        run: |
          echo "Configuring Git user..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Step 6: Commit and Push Changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Adding json to git..."
          git add json
          echo "Git status after add:"
          git status
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Committing changes..."
            git commit -m "${{ github.event.inputs.commit_message || 'Rename JSON files in json/December 13 to 44.json to 68.json and rename folder to json/3' }}"
            echo "Pushing changes..."
            git push origin main
          fi