name: Rename JSON Files and Screen Time Folder in json

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message for renaming JSON files and Screen Time folder'
        required: false
        default: 'Rename JSON files in json/Screen Time to 92.json to 125.json and rename folder to json/5'

jobs:
  rename_files_and_folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main

      # Step 2: Debug json Folder Contents
      - name: List json Folder Contents
        run: |
          echo "Listing contents of json folder:"
          ls -laR json || echo "json folder is empty or does not exist."
          shopt -s nocaseglob
          if ls json/[Ss][Cc][Rr][Ee][Ee][Nn][[:space:]][Tt][Ii][Mm][Ee] 2>/dev/null; then
            folder=$(ls -d json/[Ss][Cc][Rr][Ee][Ee][Nn][[:space:]][Tt][Ii][Mm][Ee] | head -n 1)
            echo "Found folder: $folder"
            ls -la "$folder"
          else
            echo "json/Screen Time folder (any case) does not exist."
          fi
          shopt -u nocaseglob

      # Step 3: Rename JSON Files in json/Screen Time
      - name: Rename JSON Files
        run: |
          echo "Renaming JSON files in json/Screen Time to 92.json to 125.json..."
          shopt -s nocaseglob
          folder=$(ls -d json/[Ss][Cc][Rr][Ee][Ee][Nn][[:space:]][Tt][Ii][Mm][Ee] 2>/dev/null | head -n 1)
          if [ -n "$folder" ] && [ -d "$folder" ]; then
            # Define the mapping list as an array with adjusted numbers (1->92, 2->93, ..., 34->125)
            declare -A title_map=(
              ["From the start"]="92"
              ["Reverse"]="93"
              ["Get on with Jack"]="94"
              ["Too deep"]="95"
              ["Andalucía"]="96"
              ["Friends"]="97"
              ["Text"]="98"
              ["Sunny"]="99"
              ["Humming"]="100"
              ["Waves"]="101"
              ["Addison Rae"]="102"
              ["Pauline"]="103"
              ["Skyline grey"]="104"
              ["Bittersweet"]="105"
              ["Over you"]="106"
              ["Dreaming"]="107"
              ["Relapse holding"]="108"
              ["Not lost"]="109"
              ["Hideaway"]="110"
              ["Superficial"]="111"
              ["Warning sign"]="112"
              ["Tears to my heart"]="113"
              ["I'm sorry"]="114"
              ["Yearning"]="115"
              ["Silver all gone"]="116"
              ["Your eyes"]="117"
              ["Hold over me"]="118"
              ["A minute"]="119"
              ["Mariam"]="120"
              ["Mine"]="121"
              ["Back home"]="122"
              ["Heaven knows"]="123"
              ["Assets"]="124"
              ["Just us two"]="125"
            )
            # Loop through JSON files in the folder
            for file in "$folder"/*.json; do
              if [ -f "$file" ]; then
                # Extract title by removing .json extension
                filename=$(basename "$file" .json)
                title="$filename"
                echo "Processing file: $file (extracted title: $title)"
                # Convert title to lowercase for case-insensitive matching
                title_lower=$(echo "$title" | tr '[:upper:]' '[:lower:]')
                matched=false
                # Loop through title_map to find a match
                for list_title in "${!title_map[@]}"; do
                  list_title_lower=$(echo "$list_title" | tr '[:upper:]' '[:lower:]')
                  # Check if all significant words in list_title appear in title_lower
                  match=true
                  # Split list_title into words (ignoring spaces, punctuation)
                  for word in $list_title_lower; do
                    if ! echo "$title_lower" | grep -q -w "$word"; then
                      match=false
                      break
                    fi
                  done
                  if [ "$match" = true ]; then
                    new_name="$folder/${title_map[$list_title]}.json"
                    echo "Matched '$title' to '$list_title', renaming to $new_name"
                    mv "$file" "$new_name" || echo "Failed to rename $file to $new_name"
                    matched=true
                    break
                  fi
                done
                if [ "$matched" = false ]; then
                  echo "No match found for '$title'"
                fi
              fi
            done
          else
            echo "json/Screen Time folder (any case) not found. Skipping JSON file renaming."
          fi
          shopt -u nocaseglob

      # Step 4: Rename json/Screen Time Folder to json/5
      - name: Rename Screen Time Folder
        run: |
          echo "Renaming json/Screen Time to json/5..."
          shopt -s nocaseglob
          folder=$(ls -d json/[Ss][Cc][Rr][Ee][Ee][Nn][[:space:]][Tt][Ii][Mm][Ee] 2>/dev/null | head -n 1)
          if [ -n "$folder" ] && [ -d "$folder" ]; then
            mv "$folder" json/5 || echo "Failed to rename $folder to json/5"
          else
            echo "json/Screen Time folder (any case) not found. Skipping folder renaming."
          fi
          shopt -u nocaseglob
          echo "Listing contents of json after renaming:"
          ls -laR json

      # Step 5: Configure Git User
      - name: Configure Git User
        run: |
          echo "Configuring Git user..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Step 6: Commit and Push Changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Adding json to git..."
          git add json
          echo "Git status after add:"
          git status
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Committing changes..."
            git commit -m "${{ github.event.inputs.commit_message || 'Rename JSON files in json/Screen Time to 92.json to 125.json and rename folder to json/5' }}"
            echo "Pushing changes..."
            git push origin main
          fi