name: Rename JSON Files and Lantern Folder in json

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message for renaming JSON files and Lantern folder'
        required: false
        default: 'Rename JSON files in json/Lantern to 184.json to 206.json and rename folder to json/8'

jobs:
  rename_files_and_folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main

      # Step 2: Debug json Folder Contents
      - name: List json Folder Contents
        run: |
          echo "Listing contents of json folder:"
          ls -laR json || echo "json folder is empty or does not exist."
          shopt -s nocaseglob
          if ls json/[Ll][Aa][Nn][Tt][Ee][Rr][Nn] 2>/dev/null; then
            folder=$(ls -d json/[Ll][Aa][Nn][Tt][Ee][Rr][Nn] | head -n 1)
            echo "Found folder: $folder"
            ls -la "$folder"
          else
            echo "json/Lantern folder (any case) does not exist."
          fi
          shopt -u nocaseglob

      # Step 3: Rename JSON Files in json/Lantern
      - name: Rename JSON Files
        run: |
          echo "Renaming JSON files in json/Lantern to 184.json to 206.json..."
          shopt -s nocaseglob
          folder=$(ls -d json/[Ll][Aa][Nn][Tt][Ee][Rr][Nn] 2>/dev/null | head -n 1)
          if [ -n "$folder" ] && [ -d "$folder" ]; then
            # Define the mapping list as an array with adjusted numbers (1->184, 2->185, ..., 23->206)
            declare -A title_map=(
              ["Do I ever do"]="184"
              ["Number busy"]="185"
              ["Emma I feel"]="186"
              ["Raunch child"]="187"
              ["Jekyll"]="188"
              ["God of clean"]="189"
              ["Hungry man"]="190"
              ["Lantern"]="191"
              ["3 30"]="192"
              ["Be my lover"]="193"
              ["Purple zone"]="194"
              ["Shire"]="195"
              ["Pussy power"]="196"
              ["Scent"]="197"
              ["Yeehaw"]="198"
              ["Mind talk"]="199"
              ["Cautious"]="200"
              ["Sarah"]="201"
              ["Call for more"]="202"
              ["Higher calling"]="203"
              ["Say it"]="204"
              ["Avalon"]="205"
              ["How I lose it"]="206"
            )
            # Loop through JSON files in the folder
            for file in "$folder"/*.json; do
              if [ -f "$file" ]; then
                # Extract title by removing .json extension
                filename=$(basename "$file" .json)
                title="$filename"
                echo "Processing file: $file (extracted title: $title)"
                # Convert title to lowercase for case-insensitive matching
                title_lower=$(echo "$title" | tr '[:upper:]' '[:lower:]')
                # Replace common separators in title_lower for matching (e.g., "3:30" to "3 30")
                title_lower=$(echo "$title_lower" | sed 's/[:_-]/ /g')
                matched=false
                # Loop through title_map to find a match
                for list_title in "${!title_map[@]}"; do
                  list_title_lower=$(echo "$list_title" | tr '[:upper:]' '[:lower:]')
                  # Check if all significant words in list_title appear in title_lower
                  match=true
                  # Split list_title into words (ignoring spaces, punctuation)
                  for word in $list_title_lower; do
                    if ! echo "$title_lower" | grep -q -w "$word"; then
                      match=false
                      break
                    fi
                  done
                  if [ "$match" = true ]; then
                    new_name="$folder/${title_map[$list_title]}.json"
                    echo "Matched '$title' to '$list_title', renaming to $new_name"
                    mv "$file" "$new_name" || echo "Failed to rename $file to $new_name"
                    matched=true
                    break
                  fi
                done
                if [ "$matched" = false ]; then
                  echo "No match found for '$title'"
                fi
              fi
            done
          else
            echo "json/Lantern folder (any case) not found. Skipping JSON file renaming."
          fi
          shopt -u nocaseglob

      # Step 4: Rename json/Lantern Folder to json/8
      - name: Rename Lantern Folder
        run: |
          echo "Renaming json/Lantern to json/8..."
          shopt -s nocaseglob
          folder=$(ls -d json/[Ll][Aa][Nn][Tt][Ee][Rr][Nn] 2>/dev/null | head -n 1)
          if [ -n "$folder" ] && [ -d "$folder" ]; then
            mv "$folder" json/8 || echo "Failed to rename $folder to json/8"
          else
            echo "json/Lantern folder (any case) not found. Skipping folder renaming."
          fi
          shopt -u nocaseglob
          echo "Listing contents of json after renaming:"
          ls -laR json

      # Step 5: Configure Git User
      - name: Configure Git User
        run: |
          echo "Configuring Git user..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Step 6: Commit and Push Changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Adding json to git..."
          git add json
          echo "Git status after add:"
          git status
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Committing changes..."
            git commit -m "${{ github.event.inputs.commit_message || 'Rename JSON files in json/Lantern to 184.json to 206.json and rename folder to json/8' }}"
            echo "Pushing changes..."
            git push origin main
          fi