name: Zip Root Folders

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message for zipped root folders'
        required: false
        default: 'Zip audio, cover, and json folders'

jobs:
  zip_folders:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit ZIP files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip root folders
        run: |
          for folder in audio cover json; do
            if [ -d "$folder" ]; then
              zip -r "${folder}.zip" "$folder"
              echo "Created ${folder}.zip"
            else
              echo "Folder not found: $folder"
            fi
          done

      - name: Commit and push ZIP files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add audio.zip cover.zip json.zip
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "${{ github.event.inputs.commit_message || 'Zip audio, cover, and json folders' }}"
            git push origin HEAD:main
          fi